### ISSUE TITLE
疑问：keyframes 中的点云是否也需要在全局优化后进行矫正

### ISSUE THREAD

**Issue by JaySlamer** [YWL0720/DLIOM#2]
keyframes中的pose 每次全局优化后会进行矫正，而cloud从未矫正过。也就是说这些cloud各自在不同的坐标系下（它们经历过不同次数的后端优化，也就是产生该keyframe时里程计被矫正过的次数，有的可能在没有经过任何后端优化时的坐标系，有的可能处在经过若干次后端优化的坐标系）。然而代码中的构建jaccard submap时 使用这些实际上处于不同坐标系的点云进行knn计算相似度。

**Comment by YWL0720** [comment]
感谢您指出的问题！在计算相似时，对历史关键帧，确实也应该使用矫正位姿后的点云。

**Comment by JaySlamer** [comment]
> 感谢您指出的问题！在计算相似时，对历史关键帧，确实也应该使用矫正位姿后的点云。

不客气。感谢你的工作，我学到很多。
